/// 《用户隐私政策》/《用户服务协议与隐私政策》的**英文正文**（译文）。
///
/// 本文件与 `lib/l10n/legal_zh.dart` 是**一对**：两边的记录字段名、顺序、类型必须
/// 逐字一致，`lib/l10n/legal.dart` 的 `legalTextsFor` 用同一个记录类型返回两边，
/// 类型不一致无法通过编译。
///
/// ⚠️ **改中文条款必须同步改本文件**——缺一个会让该语言下正文为空
/// （`test/legal_texts_test.dart` 兜底断言非空）。
///
/// 译文只做英文化，不改条款：段落、小节、编号、空行与中文版一一对应（段数、小节数
/// 相同），便于日后逐段对照维护。中文原文里的 `**...**` 强调星号在本文件中一律写成
/// 平文（正文用纯 `Text()` 渲染，不解析 Markdown，星号会原样显示）。
///
/// 应用名按仓库约定：中文「小喵Player」对应英文 `Meow Player`。
///
/// 按语言的取用入口在 `lib/l10n/legal.dart`（`legalTextsFor`）。
library;

/// 英文长文正文（四个字段与中文版 `legalZh` 一一对应）
const ({
  String policyTitle,
  String policyBody,
  String agreementTitle,
  String agreementBody,
}) legalEn = (
  policyTitle: 'User Privacy Policy',
  policyBody: '''
Welcome to "Meow Player" (hereinafter "this App"). This App is an open-source, free local video player. We understand how important your personal information is to you, and we will do our utmost to keep it safe. Before using this App, please read this User Privacy Policy (hereinafter "this Policy") carefully and make sure you fully understand it. By checking the box to agree and starting to use this App, you confirm that you fully understand and agree to all of the terms of this Policy.

I. How We Obtain and Use Permissions

To provide core features such as local video scanning, playback and network playback, this App may request the following system permissions from you. All permissions are granted entirely at your own discretion, and you have the right to refuse them; refusing a permission only makes the corresponding feature unavailable, and does not affect your use of the other basic features of this App:

1. Storage permission (read / manage all files): used to scan, index and play local video files on your device. This App will not read or collect the contents of any other files unrelated to videos.
2. Network permission: used for the network access required by online playback, anime integration, danmaku, update checks and similar features.
3. Notification permission (Android 13 and above): used only while you use Listen for background playback, to show the current playback status in the notification shade (keeping the foreground service alive). This App does not use it to push download progress, update reminders or any marketing notifications.
4. Other system permissions (such as picture-in-picture and foreground service): used for background playback, picture-in-picture and similar features.

None of the permissions above will be enabled without your authorization, and this App will not collect any of your information in the background.

II. Account Sign-In and Credential Information

This App provides Bilibili account sign-in (including QR code sign-in and Cookie import). When you choose to sign in, this App obtains the login credentials you provide voluntarily, such as Token and Cookie values (SESSDATA, bili_jct and others).

1. The credentials above are used only to provide Bilibili ecosystem features such as anime browsing, online playback, danmaku and downloads, and are never used for any other purpose.
2. Your login credentials are stored in encrypted form locally on your device. We keep your credential information strictly confidential, and will not upload, download, sell or share it, or provide it to any third party in any form.
3. This App operates no servers of any kind, and will not upload your credentials or any personal data to any server.
4. You can sign out at any time on the Mine page; once you sign out, your local credentials are cleared.

III. Data Storage and Servers

1. This App is a purely local application. It sets up and operates no servers, and will not collect, upload or store any of your personal information or usage data.
2. Apart from network features that you initiate yourself (such as online playback, fetching danmaku and update checks), this App performs no data transmission in the background.
3. Data generated by this App, such as caches, playback progress, settings and downloaded files, is stored locally on your device, and is managed and cleared by you.

IV. Third-Party Components and Open-Source Code

This App is built on an open-source project and integrates a large number of third-party open-source components (including but not limited to media_kit, canvas_danmaku and components from the Flutter ecosystem), and it connects to publicly available Bilibili-related interfaces. Those third-party components and interfaces are governed by their own license agreements; any data collection they perform (if any) is the responsibility of their providers and is unrelated to this App.

Online subtitle search: when you use the Subtitle Download feature, this App sends the title (film or show name) you enter to the subtitle service you have selected, solely to look up subtitles — it is sent to sub.wyzie.io if you choose the Wyzie subtitles service, or to the address you filled in yourself if you choose a custom subtitle address (that address is operated by its provider and is unrelated to this App). This App neither bundles nor proxies any third-party subtitle service, and sends no data when no search is started. Please confirm the terms and availability of the service you enter yourself, and bear the consequences of using that service yourself.

V. Bilibili Ecosystem Integration and Risk Notice

1. The Bilibili-related features integrated into this App (anime, playback, danmaku, downloads and so on) are all implemented on the basis of publicly available information and public interfaces found on the internet. This App has no affiliation, partnership or other relationship with Bilibili itself.
2. When you sign in to a Bilibili account through this App or perform related operations, you must comply with the relevant user agreements and rules of the Bilibili platform. If your Bilibili account is restricted, rate-limited, banned or otherwise affected, or you suffer any other loss, as a result of your own use (including but not limited to high-frequency requests, bulk downloads or violations of platform rules), it is unrelated to this App and to the developer of this App, and you bear the responsibility yourself.

VI. Free of Charge and Ad-Free Statement

1. This App is open-source and free software. It contains no advertising, and involves no charges of any kind.
2. If you encounter any advertising, charges, membership unlocking or similar behaviour while using this App, it is not done by this App or by the developer of this App. It must come from another organization or individual that modified the open-source code of this project and redistributed it separately. Please stop using it and carefully verify where it came from.

VII. API Use and Copyright Statement

1. All APIs used by this App (especially the Bilibili anime-related APIs) are implemented on the basis of publicly available information currently found on the internet.
2. If any content involved in this App infringes the interests or copyright of any party, that party may contact the developer of this App, and this App will cooperate in taking it down or deleting it after verification.

VIII. Protection of Minors and Miscellaneous

1. If you are a minor, please read this Policy under the guidance of your guardian and decide whether to use this App.
2. This Policy may be revised from time to time due to feature updates, changes in laws and regulations, and other reasons; the revised Policy will be published within this App.

IX. Contact Us

If you have any questions, suggestions or complaints about this Policy or this App, you can contact us in the following way:
Email: 2297065843@qq.com
''',
  agreementTitle: 'User Service Agreement and Privacy Policy',
  agreementBody: '''
Welcome to "Meow Player" (hereinafter "this App"). Before using this App, please read this User Service Agreement and Privacy Policy (hereinafter "this Agreement") carefully and make sure you fully understand it. This Agreement consists of two parts, the User Service Agreement and the Privacy Policy, and forms the complete arrangement between you and the developer of this App.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Part One User Service Agreement

I. Service Description

This App is an open-source, free local video player. It provides local video scanning and playback, direct-link online playback, subtitles and danmaku, audio enhancement, casting, network storage, Bilibili ecosystem integration (anime, danmaku and downloads) and other features.

II. Free and Open-Source Statement

1. This App is completely free and open-source. It contains no advertising, and involves no form of charging.
2. If you encounter any advertising, charges, membership unlocking or similar behaviour while using this App, it is not done by this App or by the developer of this App. It must come from another organization or individual that modified the open-source code of this project and redistributed it separately. Please stop using it immediately and carefully verify where it came from.

III. User Conduct Rules

1. You must use this App lawfully and in compliance with applicable regulations, and must not use it to engage in any conduct that violates laws or regulations or infringes the lawful rights and interests of others.
2. The copyright in the network interfaces, anime content and danmaku content involved in this App belongs to their original rights holders.

IV. Third-Party Platform Accounts

1. The Bilibili account sign-in provided by this App is used only to provide users with ecosystem features such as anime browsing, online playback, danmaku and downloads.
2. When you sign in to a Bilibili account through this App or perform related operations, you must comply with the relevant user agreements and rules of the Bilibili platform.
3. If your Bilibili account is restricted, rate-limited, banned or otherwise affected, or you suffer any other loss, as a result of your own use (including but not limited to high-frequency requests, bulk downloads or violations of platform rules), it is unrelated to this App and to the developer of this App, and you bear the responsibility yourself.

V. Disclaimer

1. All APIs integrated into this App (especially the Bilibili anime-related APIs) are implemented on the basis of publicly available information currently found on the internet. This App does not guarantee the continued availability or stability of those interfaces.
2. This App accepts no responsibility for features that malfunction or become unavailable due to interface changes, platform risk controls, network conditions, third-party services or similar causes.

VI. Copyright and Intellectual Property

1. The source code of this App is released under its open-source license; the intellectual property in the name, interface design and other aspects of this App belongs to the developer of this App.
2. If any content involved in this App infringes the interests or copyright of any party, that party may contact the developer of this App, and this App will cooperate in taking it down or deleting it after verification.

VII. Changes to This Agreement

This Agreement may be revised from time to time due to feature updates, changes in laws and regulations, and other reasons. The revised Agreement will be published within this App, and continued use of this App is taken as your acceptance of the revised Agreement.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Part Two Privacy Policy

I. How We Obtain and Use Permissions

To provide core features such as local video scanning, playback and network playback, this App may request the following system permissions from you. All permissions are granted entirely at your own discretion, and you have the right to refuse them; refusing a permission only makes the corresponding feature unavailable, and does not affect your use of the other basic features of this App:

1. Storage permission (read / manage all files): used to scan, index and play local video files on your device. This App will not read or collect the contents of any other files unrelated to videos.
2. Network permission: used for the network access required by online playback, anime integration, danmaku, update checks and similar features.
3. Notification permission (Android 13 and above): used only while you use Listen for background playback, to show the current playback status in the notification shade (keeping the foreground service alive). This App does not use it to push download progress, update reminders or any marketing notifications.
4. Other system permissions (such as picture-in-picture and foreground service): used for background playback, picture-in-picture and similar features.

None of the permissions above will be enabled without your authorization, and this App will not collect any of your information in the background.

II. Account Sign-In and Credential Information

This App provides Bilibili account sign-in (including QR code sign-in and Cookie import). When you choose to sign in, this App obtains the login credentials you provide voluntarily, such as Token and Cookie values (SESSDATA, bili_jct and others).

1. The credentials above are used only to provide Bilibili ecosystem features such as anime browsing, online playback, danmaku and downloads, and are never used for any other purpose.
2. Your login credentials are stored in encrypted form locally on your device. We keep your credential information strictly confidential, and will not upload, download, sell or share it, or provide it to any third party in any form.
3. This App operates no servers of any kind, and will not upload your credentials or any personal data to any server.
4. You can sign out at any time on the Mine page; once you sign out, your local credentials are cleared.

III. Data Storage and Servers

1. This App is a purely local application. It sets up and operates no servers, and will not collect, upload or store any of your personal information or usage data.
2. Apart from network features that you initiate yourself (such as online playback, fetching danmaku and update checks), this App performs no data transmission in the background.
3. Data generated by this App, such as caches, playback progress, settings and downloaded files, is stored locally on your device, and is managed and cleared by you.

IV. Third-Party Components and Open-Source Code

This App is built on an open-source project and integrates a large number of third-party open-source components (including but not limited to media_kit, canvas_danmaku and components from the Flutter ecosystem), and it connects to publicly available Bilibili-related interfaces. Those third-party components and interfaces are governed by their own license agreements; any data collection they perform (if any) is the responsibility of their providers and is unrelated to this App.

Online subtitle search: when you use the Subtitle Download feature, this App sends the title (film or show name) you enter to the subtitle service you have selected, solely to look up subtitles — it is sent to sub.wyzie.io if you choose the Wyzie subtitles service, or to the address you filled in yourself if you choose a custom subtitle address (that address is operated by its provider and is unrelated to this App). This App neither bundles nor proxies any third-party subtitle service, and sends no data when no search is started. Please confirm the terms and availability of the service you enter yourself, and bear the consequences of using that service yourself.

V. Protection of Minors

If you are a minor, please read this Agreement under the guidance of your guardian and decide whether to use this App.

VI. Contact Us

If you have any questions, suggestions or complaints about this Agreement or this App, you can contact us in the following way:
Email: 2297065843@qq.com
''',
);
